// @ts-nocheck
import { GuildMember } from 'discord.js';
import { spawn } from 'child_process';
import fs from 'fs';
import path from 'path';
import https from 'https';
const voice:any=require('@discordjs/voice');
const YTDlpWrap:any=require('yt-dlp-wrap').default||require('yt-dlp-wrap');
const ffmpegPath=require('ffmpeg-static');
type Track={title:string;url:string;duration:number;thumbnail?:string|null;requestedTitle?:string};
type P={guildId:string;connection:any;player:any;queue:Track[];current:Track|null;loop:'off'|'track'|'queue';volume:number;playing:boolean;transitioning:boolean;generation:number;ytdlpProcess:any;ffmpegProcess:any;audioResource:any};
const players=new Map<string,P>();
const binDir=path.join(__dirname,'..','..','data'); const ytDlpPath=path.join(binDir,process.platform==='win32'?'yt-dlp.exe':'yt-dlp'); let yt:any=null;
const isHttp=(v:string)=>/^https?:\/\//i.test(String(v||'').trim());
function ytUrl(v:string){try{const u=new URL(String(v||'').trim()),h=u.hostname.toLowerCase().replace(/^www\./,'');return ['youtube.com','m.youtube.com','music.youtube.com','youtu.be'].includes(h)}catch{return false}}
function ytPlaylist(v:string){try{const u=new URL(v),h=u.hostname.toLowerCase().replace(/^www\./,'');return ['youtube.com','m.youtube.com','music.youtube.com'].includes(h)&&u.pathname==='/playlist'&&u.searchParams.has('list')}catch{return false}}
function spotify(v:string){try{const u=new URL(v);if(!['open.spotify.com','www.open.spotify.com'].includes(u.hostname))return null;const p=u.pathname.split('/').filter(Boolean),i=p.findIndex(x=>['track','playlist','album'].includes(x));return i>=0&&p[i+1]?{type:p[i],id:p[i+1]}:null}catch{return null}}
async function init(){fs.mkdirSync(binDir,{recursive:true});if(!fs.existsSync(ytDlpPath))await YTDlpWrap.downloadFromGithub(ytDlpPath);yt=new YTDlpWrap(ytDlpPath);}
function ensure(){if(!yt)throw new Error('Müzik altyapısı henüz hazır değil.');return yt;}
function requestText(url:string){return new Promise<string>((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36'}},res=>{let b='';res.setEncoding('utf8');res.on('data',c=>b+=c);res.on('end',()=>{if((res.statusCode||0)<200||(res.statusCode||0)>=300)return reject(new Error(`YouTube HTTP ${res.statusCode}`));resolve(b)})});req.on('error',reject);req.setTimeout(15000,()=>req.destroy(new Error('YouTube isteği zaman aşımına uğradı.')))});}
async function search(q:string):Promise<Track>{const b=await requestText(`https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`);const m=b.match(/"videoId":"([^"]+)"/);if(!m)throw new Error(`YouTube'da sonuç bulunamadı: ${q}`);const id=m[1];return {title:q,url:`https://www.youtube.com/watch?v=${id}`,duration:0,thumbnail:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`}}
async function resolveVideo(url:string):Promise<Track>{const out=await ensure().execPromise([url,'--dump-single-json','--no-playlist','--no-warnings','--skip-download']);const d=JSON.parse(out);if(!d.id)throw new Error('YouTube videosu çözümlenemedi.');return {title:d.title||'YouTube',url:d.webpage_url||`https://www.youtube.com/watch?v=${d.id}`,duration:Number(d.duration||0),thumbnail:d.thumbnail||null}}
async function resolvePlaylist(url:string){const out=await ensure().execPromise([url,'--flat-playlist','--dump-single-json','--no-warnings','--skip-download']);const d=JSON.parse(out),e=(d.entries||[]).filter(Boolean);if(!e.length)throw new Error('YouTube playlist boş veya çözümlenemedi.');return e.map((x:any)=>({title:x.title||`YouTube Video ${x.id}`,url:x.webpage_url||`https://www.youtube.com/watch?v=${x.id}`,duration:Number(x.duration||0),thumbnail:x.thumbnail||null})).filter((x:any)=>x.url)}
async function spotifyTitle(url:string){return new Promise<string>((resolve,reject)=>{https.get(`https://open.spotify.com/oembed?url=${encodeURIComponent(url)}`,{headers:{'User-Agent':'Mozilla/5.0'}},res=>{let b='';res.setEncoding('utf8');res.on('data',c=>b+=c);res.on('end',()=>{try{resolve(String(JSON.parse(b).title||'').trim())}catch{reject(new Error('Spotify bilgisi okunamadı.'))}})}).on('error',reject)})}
async function resolve(q:string):Promise<Track[]>{q=String(q||'').trim();if(!q)throw new Error('Bir şarkı adı veya bağlantı girmelisin.');const sp=spotify(q);if(sp){if(sp.type!=='track')throw new Error('Spotify playlist/albüm bağlantıları şu aşamada desteklenmiyor.');const title=await spotifyTitle(q);const t=await search(title);return [{...t,requestedTitle:title}]}if(isHttp(q)){if(ytPlaylist(q))return resolvePlaylist(q);if(ytUrl(q))return [await resolveVideo(q)];throw new Error('Desteklenmeyen bağlantı. YouTube veya Spotify kullanabilirsin.')}return [await search(q)]}
function cleanup(p:P){const f=p.ffmpegProcess,y=p.ytdlpProcess;p.ffmpegProcess=null;p.ytdlpProcess=null;p.audioResource=null;try{f?.stdin?.destroy()}catch{}try{f?.stdout?.destroy()}catch{}try{f?.stderr?.destroy()}catch{}try{if(f&&!f.killed)f.kill()}catch{}try{y?.stdout?.destroy()}catch{}try{y?.stderr?.destroy()}catch{}try{if(y&&!y.killed)y.kill()}catch{}}
function stream(url:string){const args=[url,'--no-playlist','--no-warnings','--quiet','--js-runtimes','node','--remote-components','ejs:npm','--extractor-args','youtube:player_client=android','-f','18','-o','-'];console.log('[yt-dlp] Stream başlatılıyor:',url);const proc=spawn(ytDlpPath,args,{stdio:['ignore','pipe','pipe'],windowsHide:true});proc.stderr.on('data',(d:any)=>{const t=String(d).trim();if(t)console.error('[yt-dlp]',t)});proc.on('error',(e:any)=>console.error('[yt-dlp] Process hatası:',e.message));return {stream:proc.stdout,process:proc}}
function make(guildId:string):P{const p:any={guildId,connection:null,player:voice.createAudioPlayer({behaviors:{noSubscriber:voice.NoSubscriberBehavior.Pause}}),queue:[],current:null,loop:'off',volume:.8,playing:false,transitioning:false,generation:0,ytdlpProcess:null,ffmpegProcess:null,audioResource:null};p.player.on(voice.AudioPlayerStatus.Idle,()=>{if(!p.transitioning&&p.playing){p.playing=false;next(p).catch((e:any)=>console.error('[Müzik] next:',e.message))}});p.player.on('error',(e:any)=>{console.error(`[${guildId}] Player error:`,e.message);p.playing=false;cleanup(p);if(!p.transitioning)next(p).catch(()=>{})});return p}
function get(g:string){let p=players.get(g);if(!p){p=make(g);players.set(g,p)}return p}
async function connect(member:GuildMember,p:P){const ch=member.voice.channel;if(!ch)throw new Error('Önce bir ses kanalına gir.');if(p.connection&&p.connection.joinConfig?.channelId!==ch.id)throw new Error('Bot şu anda başka bir ses kanalında.');const existing=voice.getVoiceConnection(member.guild.id);const connection=existing||voice.joinVoiceChannel({channelId:ch.id,guildId:member.guild.id,adapterCreator:member.guild.voiceAdapterCreator,selfDeaf:true});p.connection=connection;p.connection.subscribe(p.player);try{await voice.entersState(p.connection,voice.VoiceConnectionStatus.Ready,15000)}catch(e){console.error('[Müzik] Voice Ready beklenirken:',e?.message||e)} }
async function playItem(p:P,item:Track){p.transitioning=true;const gen=++p.generation;cleanup(p);p.current=item;const r=stream(item.url);p.ytdlpProcess=r.process;const input=r.stream;input.on('error',(e:any)=>{if(gen!==p.generation)return;if(!['ERR_STREAM_PREMATURE_CLOSE','ERR_STREAM_DESTROYED','EPIPE'].includes(e.code))console.error('[Müzik] yt-dlp stream:',e.message)});const ff=spawn(ffmpegPath,['-hide_banner','-loglevel','error','-i','pipe:0','-vn','-f','s16le','-ar','48000','-ac','2','pipe:1'],{stdio:['pipe','pipe','pipe'],windowsHide:true});p.ffmpegProcess=ff;ff.stderr.on('data',(d:any)=>{if(gen===p.generation){const t=String(d).trim();if(t)console.error('[FFmpeg]',t)}});ff.on('error',(e:any)=>{if(gen===p.generation)console.error('[Müzik] FFmpeg:',e.message)});ff.stdin.on('error',()=>{});input.pipe(ff.stdin);const resource=voice.createAudioResource(ff.stdout,{inputType:voice.StreamType.Raw,inlineVolume:true});p.audioResource=resource;resource.volume.setVolume(p.volume);p.playing=true;p.transitioning=false;p.player.play(resource);console.log(`[${p.guildId}] AudioPlayer oynatmaya başladı: ${item.title}`)}
async function next(p:P){if(p.transitioning)return;p.transitioning=true;try{if(!p.current){const i=p.queue.shift();if(!i){p.transitioning=false;return}await playItem(p,i);return}const done=p.current;if(p.loop==='track'){await playItem(p,done);return}if(p.loop==='queue')p.queue.push(done);const i=p.queue.shift();if(!i){p.current=null;p.playing=false;cleanup(p);p.transitioning=false;return}await playItem(p,i)}catch(e:any){console.error('[Müzik] Next:',e.message);cleanup(p);p.current=null;p.playing=false;p.transitioning=false;if(p.queue.length)setTimeout(()=>next(p).catch(()=>{}),500)}}
export async function playTrack(member:GuildMember,q:string){await init();const p=get(member.guild.id);await connect(member,p);const items=await resolve(q);if(p.queue.length+items.length>100)throw new Error('Kuyruk limiti 100 parça.');const idle=!p.current&&!p.playing&&!p.transitioning;p.queue.push(...items);if(idle)await next(p);return items[0]}
export function queue(g:string){return players.get(g)?.queue.slice()||[]}export function current(g:string){return players.get(g)?.current||null}
export function skip(g:string){const p=players.get(g);if(!p?.current)return false;p.transitioning=true;++p.generation;p.playing=false;p.player.stop(true);cleanup(p);p.transitioning=false;setImmediate(()=>next(p).catch(()=>{}));return true}
export function stop(g:string){const p=players.get(g);if(!p)return;p.transitioning=true;++p.generation;p.playing=false;p.queue=[];p.current=null;p.player.stop(true);cleanup(p);try{p.connection?.destroy()}catch{}p.connection=null;p.transitioning=false;players.delete(g)}
export function pause(g:string){return !!players.get(g)?.player.pause()}export function resume(g:string){return !!players.get(g)?.player.unpause()}export function setVolume(g:string,l:number){const p=players.get(g);if(!p)return false;p.volume=Math.max(0,Math.min(100,l))/100;p.audioResource?.volume?.setVolume(p.volume);return true}export function setLoop(g:string,m:'off'|'track'|'queue'){const p=get(g);p.loop=m;return m}export function shuffle(g:string){const p=players.get(g);if(!p)return false;for(let i=p.queue.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p.queue[i],p.queue[j]]=[p.queue[j],p.queue[i]]}return true}export function remove(g:string,pos:number){const p=players.get(g);if(!p||pos<1||pos>p.queue.length)return null;return p.queue.splice(pos-1,1)[0]}export async function initMusic(){await init()}
